# Generated by Django 3.2.16 on 2022-12-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_imageg',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA7GbKZJfH2z_BfU46jgCuiv2y73UaR0gpQg&usqp=CAU', max_length=500),
        ),
    ]
