# Generated by Django 3.2.16 on 2022-12-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_imageg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_imageg',
            new_name='item_image',
        ),
    ]
